on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.8
          - 1.9
          - 1.10

    container: elixir:${{ matrix.elixir }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get

      - name: Run tests
        run: mix test
